Update and rename Job_S+F.yml to Job_S_F.yml

diff --git a/.github/workflows/Job_S_F.yml b/.github/workflows/Job_S_F.yml
--- a/.github/workflows/Job_S_F.yml
+++ b/.github/workflows/Job_S_F.yml
@@ -7,14 +7,14 @@ jobs:
     runs-on: ubuntu-latest 
     steps:
     - name: Print Hello World
-     run: echo "This is Job 1"
+      run: echo "This is Job 1"
 
   Job2:
     needs: Job1
     runs-on: ubuntu-latest 
     steps:
     - name: Print Hello World
-     run: exit 1
+      run: exit 1
 
   Job3:
     needs: [Job1,Job2]
@@ -22,4 +22,4 @@ jobs:
     if: ${{ failure('Job2') }}
     steps:
     - name: Prepare Configuration
-     run: echo "Job 2 executed weather job 1 fails or succeed."
+      run: echo "Job 2 executed weather job 1 fails or succeed."
